name: MLOps CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10

    - name: Install training dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Training Pipeline
      run: |
        python -m src.data_ingestion.data_ingestion
        python -m src.feature_engineering.feature_engineering
        python -m src.data_preprocessing.data_preprocessing
        python -m src.model_training.train
        python -m src.model_training.evaluate

    - name: Build Docker Image
      run: |
        docker build -t churn-api .